In [3]:
#importing libraries
import numpy as np
import pandas as pd
import sys

In [4]:
# confirming the environment variables
print("Python :", sys.version.split()[0])
print("Numpy :", np.__version__)
print("pandas :", pd.__version__)

Python : 3.12.10
Numpy : 2.5.3
pandas : 3.0.6

In [5]:
# import path
from pathlib import Path

In [6]:
RAW = Path("../data/raw")
PROCESSED = Path("../data/processed")

In [7]:
for file in RAW.glob("*.csv"):
    print(file.name)

Bookings_2023 (1).csv
Bookings_2024 (1).csv
Bookings_2025 (1).csv

In [9]:
#Working with pandas to work on the data
#Loading data using Pandas
df_2023 = pd.read_csv(RAW / "Bookings_2023 (1).csv")
df_2024 = pd.read_csv(RAW / "Bookings_2024 (1).csv")
df_2025 = pd.read_csv(RAW / "Bookings_2025 (1).csv")

In [10]:
#Inspecting data using pandas
df_2023.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,Completed,Bank Transfer
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,Completed,Card
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,Completed,PayPal
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,Completed,Card
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,Completed,Bank Transfer

In [11]:
#shape
df_2024.shape

(4626, 12)

In [13]:
#columns
df_2024.columns

Index(['BookingID', 'BookingDate', 'TravelStartDate', 'CustomerID',
       'PackageID', 'AgentID', 'Adults', 'Children', 'UnitPriceUSD',
       'DiscountPct', 'Status', 'PaymentMethod'],
      dtype='str')

In [14]:
#data types 
df_2024.dtypes

BookingID              str
BookingDate            str
TravelStartDate        str
CustomerID             str
PackageID              str
AgentID                str
Adults               int64
Children             int64
UnitPriceUSD         int64
DiscountPct        float64
Status                 str
PaymentMethod          str
dtype: object

In [15]:
df_2023.describe(include ="all")

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod
count,3867,3867,3867,3867,3867,2767,3867.000000,3867.000000,3867.000000,3747.000000,3867,3867
unique,3867,365,557,2946,17,13,NaN,NaN,NaN,NaN,9,4
top,BK-2023-00001,2023-06-21,2023-07-11,C01058,PK06,AG03,NaN,NaN,NaN,NaN,Completed,Card
freq,1,27,26,4,409,401,NaN,NaN,NaN,NaN,3221,1727
mean,NaN,NaN,NaN,NaN,NaN,NaN,2.970261,0.531161,2718.250582,0.039672,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,2.382879,0.983437,2516.887252,0.048234,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,380.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,0.000000,620.000000,0.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,0.000000,1440.000000,0.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,1.000000,4485.000000,0.100000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,12.000000,3.000000,11835.000000,0.150000,NaN,NaN

In [16]:
#Merging datasets
df = pd.concat([df_2023, df_2024, df_2025], ignore_index=True)

In [17]:
print(df.shape)

(13927, 12)

In [20]:
#Checking for duplicates
df["BookingID"].duplicated().sum

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
13922    False
13923    False
13924    False
13925    False
13926    False
Name: BookingID, Length: 13890, dtype: bool>

In [95]:
#Clean duplicates
df = df.drop_duplicates(subset="BookingID", keep= "first")

In [111]:
#Missing values
df.isna().sum()

BookingID          0
BookingDate        0
TravelStartDate    0
CustomerID         0
PackageID          0
AgentID            0
Adults             0
Children           0
UnitPriceUSD       0
DiscountPct        0
Status             0
PaymentMethod      0
BookingYear        0
Travellers         0
Grossvalue         0
DiscountAmount     0
BookingCategory    0
dtype: int64

In [110]:
# clean missing values
df["AgentID"] = df["AgentID"].fillna("Unknown")
df["DiscountPct"] = df["DiscountPct"].fillna(0)

In [37]:
#Check data quality on status column
df["Status"].value_counts(dropna=False)

Status
completed    12408
cancelled     1312
confirmed      170
Name: count, dtype: int64[pyarrow]

In [38]:
df["Status"].unique()

<ArrowStringArray>
['completed', 'cancelled', 'confirmed']
Length: 3, dtype: string

In [36]:
#Cleaning the status column
df["Status"] = df["Status"].astype("string").str.strip().str.lower().replace({"canceled": "cancelled"})

In [39]:
#Clean dates column
df["BookingDate"] = pd.to_datetime(df["BookingDate"], errors = "coerce")

In [43]:
#Extract data from booking date column
df["BookingYear"] = df["BookingDate"].dt.year
df["BookingYear"] = df["BookingDate"].dt.month

In [45]:
df.shape

(13890, 13)

In [ ]:
#Finding data using position in Pandas
df.iloc[1]

BookingID                BK-2023-00002
BookingDate        2023-01-01 00:00:00
TravelStartDate             2023-07-07
CustomerID                      C01980
PackageID                         PK09
AgentID                           AG02
Adults                               1
Children                             0
UnitPriceUSD                      2990
DiscountPct                        0.0
Status                       completed
PaymentMethod                     Card
BookingYear                          1
Name: 1, dtype: object

In [47]:
df.iloc[1:3]

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.0,completed,Card,1
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.0,completed,PayPal,1

In [48]:
df.iloc[1:6, 3:6]

  CustomerID PackageID  AgentID
1     C01980      PK09     AG02
2     C01992      PK15     AG08
3     C02537      PK06  Unknown
4     C03846      PK01  Unknown
5     C04189      PK02  Unknown

In [49]:
df.iloc[4][["BookingID","PackageID"]]

BookingID    BK-2023-00005
PackageID             PK01
Name: 4, dtype: object

In [50]:
df.loc[:,"BookingID"]

0        BK-2023-00001
1        BK-2023-00002
2        BK-2023-00003
3        BK-2023-00004
4        BK-2023-00005
             ...
13922    BK-2025-05430
13923    BK-2025-05431
13924    BK-2025-05432
13925    BK-2025-05433
13926    BK-2025-05434
Name: BookingID, Length: 13890, dtype: str

In [56]:
df.loc[df["UnitPriceUSD"] > 12000, ["BookingID", "BookingYear", "UnitPriceUSD"]].head(100).to_csv("UnitPriceUSD")

In [55]:
df.loc[df["PaymentMethod"] == "MPesa"].head(100)

Empty DataFrame
Columns: [BookingID, BookingDate, TravelStartDate, CustomerID, PackageID, AgentID, Adults, Children, UnitPriceUSD, DiscountPct, Status, PaymentMethod, BookingYear]
Index: []

In [57]:
#first array
data = np.array([10,29,39,46])
print(data)

[10 29 39 46]

In [58]:
print(data.dtype)

int64

In [59]:
print(data.shape)

(4,)

In [60]:
#memory size
print(data.nbytes)

32

In [61]:
#number of dimensions
print(data.ndim)

1

In [109]:
#creating an array from existing tabular data
df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,Travellers,Grossvalue,DiscountAmount,BookingCategory
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,1,2,1250,1250.00,Ndogo
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,1,1,2990,2990.00,Ndogo
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,1,5,4485,4485.00,Kubwa
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,Unknown,1,0,1250,0.00,completed,Card,1,1,1250,1250.00,Ndogo
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,Unknown,1,0,420,0.15,completed,Bank Transfer,1,1,420,419.85,Ndogo

In [64]:
Children = df_2023["Children"].to_numpy()

In [65]:
print(Children)

[0 0 3 ... 0 0 0]

In [66]:
Jose = np.zeros(4)

In [67]:
print(Jose)

[0. 0. 0. 0.]

In [74]:
discount = df_2023["DiscountPct"].to_numpy()
print(discount)

[0.   0.   0.   ... 0.1  0.05 0.  ]

In [73]:
prices= df_2023["UnitPriceUSD"].to_numpy()
print(prices)

[1250 2990 4485 ...  460  650 4710]

In [75]:
print(data)

[10 29 39 46]

In [76]:
values_above_10 = data > 10
print(values_above_10)

[False  True  True  True]

In [78]:
top_paid_bookings = prices > 10000
print(top_paid_bookings)

[False False False ... False False False]

In [79]:
Revelation_pack = df_2023[["Adults", "Children"]].to_numpy()
print(Revelation_pack)

[[2 0]
 [1 0]
 [2 3]
 ...
 [9 0]
 [1 0]
 [2 0]]

In [80]:
print(Revelation_pack.ndim)

2

In [81]:
print(Revelation_pack.shape)

(3867, 2)

In [82]:
Total_price_paid = prices.sum()
print(Total_price_paid)

10511475

In [83]:
sum_leslie = Revelation_pack[:, 1].sum()
print(sum_leslie)

2054

In [87]:
print(adults.shape)
print(children.shape)

NameError: name 'adults' is not defined

In [114]:
#using panda and numpy to create business measures
#1.
#2.
#3.
#finding Travellers




df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,Travellers,Grossvalue,DiscountAmount,BookingCategory,DiscountTier
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,1,2,1250,1250.00,Ndogo,No discount
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,1,1,2990,2990.00,Ndogo,No discount
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,1,5,4485,4485.00,Kubwa,No discount
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,Unknown,1,0,1250,0.00,completed,Card,1,1,1250,1250.00,Ndogo,No discount
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,Unknown,1,0,420,0.15,completed,Bank Transfer,1,1,420,419.85,Ndogo,High

In [90]:
df["Travellers"] = df["Adults"] + df["Children"]

In [91]:
df["Grossvalue"] = df["UnitPriceUSD"]

In [104]:
df["DiscountAmount"] = df["Grossvalue"] - df["DiscountPct"]

KeyError: 'DiscAmount'

In [108]:
#filter/classify travellers by their booking sizes
df["BookingCategory"] = np.where(
df["Travellers"] >= 4,
"Kubwa", 
"Ndogo")

In [123]:
conditions = [
    df["DiscountPct"] == 0,
    df["DiscountPct"] <= 0.10,
    df["DiscountPct"] > 0.10,
]
choices = ["No discount", "Low", "High"]

df["DiscountTier"] = np.select(conditions, choices, default="Unknown")
df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,Travellers,Grossvalue,DiscountAmount,BookingCategory,DiscountTier,NetValue
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,1,2,1250,1250.00,Ndogo,No discount,0.00
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,1,1,2990,2990.00,Ndogo,No discount,0.00
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,1,5,4485,4485.00,Kubwa,No discount,0.00
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,Unknown,1,0,1250,0.00,completed,Card,1,1,1250,1250.00,Ndogo,No discount,0.00
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,Unknown,1,0,420,0.15,completed,Bank Transfer,1,1,420,419.85,Ndogo,High,0.15

In [126]:
#Answering Busines questions?
# 1. Is the Business growing?

BusinessGrowth = (
    df.groupby("BookingYear").agg(
        Total_net_value = ("NetValue","sum"),
        Travellers_Served = ("Travellers","sum"),
        Booking_made = ("BookingID","nunique")
    )
    .reset_index()
)
BusinessGrowth.head()

   BookingYear  Total_net_value  Travellers_Served  Booking_made
0            1            34.95               3185           931
1            2            28.90               2789           787
2            3            30.75               2742           793
3            4            36.55               3306           949
4            5            44.70               4326          1206

In [122]:
df["NetValue"] = df["Grossvalue"] - df["DiscountAmount"]

In [1]:
Pharmacy sales analysis/
                |______data/
                            pharmacy_sales.csv
                |
                |______notebooks/
                                analysis.ipynb
                |
                |______src/
                            scripts.py

SyntaxError: invalid syntax (1619989682.py, line 1)